#!/bin/bash
#
# chkconfig: 2345 50 50
# description: add jar symlinks to /usr/share/tomcat6/lib

# source function library
. /etc/rc.d/init.d/functions

RETVAL=0
prog="build-jar-repository"
jar_list="log4j commons-logging mysql-connector-java"

case "$1" in
  start)
	for jar in $jar_list; do
		echo -n "$prog: Linking $jar"
		build-jar-repository /usr/share/tomcat6/lib $jar
		RETVAL=$?
		[ $RETVAL = 0 ] && echo_success || echo_failure
		echo
	done
	;;
  stop)
	echo -n "$prog: Nothing to do"
	echo_success
	echo
	;;
  status)
	RETVAL_END=0
	for jar in $jar_list; do
		echo -n "$prog: Checking $jar"
		test -L "/usr/share/tomcat6/lib/[$jar].jar"
		RETVAL=$?
		[ $RETVAL = 0 ] && echo_success || echo_failure
		[ $RETVAL != 0 ] && RETVAL_END=3
		echo
	done
	[ $RETVAL_END != 0 ] && exit $RETVAL_END
	;;
  *)	
	echo "Usage $0 {start|stop|status}"
	exit 1
esac

exit $RETVAL
